# Autogenerated wrapper script for LLVMLibcxx_jll for i686-linux-gnu
export includecxxv1_dir, libcxx, libcxxabi

using XML2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("LLVMLibcxx")
JLLWrappers.@declare_file_product(includecxxv1_dir)
JLLWrappers.@declare_library_product(libcxx, "libc++.so.1")
JLLWrappers.@declare_library_product(libcxxabi, "libc++abi.so.1")
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll, Zlib_jll)
    JLLWrappers.@init_file_product(
        includecxxv1_dir,
        "libcxx/include/c++/v1",
    )

    JLLWrappers.@init_library_product(
        libcxx,
        "libcxx/lib/libc++.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcxxabi,
        "libcxx/lib/libc++abi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
